// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PortfolioPlatform.Api.Data;

#nullable disable

namespace PortfolioPlatform.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706213000_RenameAvatarUrlToProfileImageUrl")]
    partial class RenameAvatarUrlToProfileImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only renames an existing column, so EF only needs the
            // migration metadata above to discover and apply it. The current model
            // shape is already represented by ApplicationDbContextModelSnapshot.
        }
    }
}
